services:
  web:
    build:
      context: backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./logs/daphne:/backend/logs/daphne
    env_file:
      - .envs/.django
    depends_on:
      redis:
        condition: service_started

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./logs/nginx:/var/log/nginx
    ports:
      - "83:80"
    depends_on:
      web:
        condition: service_started

  redis:
    restart: always
    image: redis:7.0.2-alpine
